#ifndef IGNISDEFINES_H
#define IGNISDEFINES_H

#define IGNIS_NX 20
#define IGNIS_NY 20

#define IGNIS_PERIODIC_X
#define IGNIS_PERIODIC_Y

#define IGNIS_VERBOSE
#define IGNIS_FILE_IO

#endif // IGNISDEFINES_H
